# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='errorlog',
            old_name='error',
            new_name='msg',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculate',
            name='error',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ErrorLog'),
        ),
    ]
