# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160918_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='error',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ErrorLog'),
        ),
        migrations.AlterField(
            model_name='data',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
